version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-wordcount-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qsu7pxy8ldun"
s3_prefix = "sam-wordcount-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SourceBucketName=\"sam-wordcount-app-src\" LoggingBucketName=\"sam-wordcount-app-logs\""

