#!/bin/bash

# Change the following five lines to deploy...
export AWS_ACCESS_KEY_ID=$((echo "${1}" | jq .aws_access_key_id) | tr -d '"' )
export AWS_SECRET_ACCESS_KEY=$((echo "${1}" | jq .aws_secret_access_key) | tr -d '"' )
export APP_NAME=$((echo "${1}" | jq .appname) | tr -d '"' )
export ECR_HOME=$((echo "${1}" | jq .container) | tr -d '"' )
export IMAGE_VERSION=$((echo "${1}" | jq .version) | tr -d '"' )
export CONTAINER_CPU=$((echo "${1}" | jq .cpu) | tr -d '"' )
export CONTAINER_RAM=$((echo "${1}" | jq .ram) | tr -d '"' )
export REGION=$((echo "${1}" | jq .region) | tr -d '"' )
export AWS_DEFAULT_REGION=${REGION}
export CONFIRM_CHANGESET=false

export DEPLOYMENT_NAME=$APP_NAME-deployment

echo "CONTAINER_RAM: ${CONTAINER_RAM}"
echo "REGION: ${REGION}"
echo "AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}"
# This is stunningly stupid...
if ! aws s3api head-bucket --bucket "$DEPLOYMENT_NAME" 2>/dev/null; then
   echo Creating S3 bucket $DEPLOYMENT_NAME
   aws s3 mb s3://$DEPLOYMENT_NAME >/dev/null
fi

rm samconfig.toml
cp samconfig_template.toml samconfig.toml

sed -i "s/DEPLOYMENT_NAME/$DEPLOYMENT_NAME/g" samconfig.toml
sed -i "s/APP_NAME/$APP_NAME/g" samconfig.toml
sed -i "s/REGION/$REGION/g" samconfig.toml
sed -i "s/CONFIRM_CHANGESET/$CONFIRM_CHANGESET/g" samconfig.toml
sed -i "s/ECR_HOME/$ECR_HOME/g" samconfig.toml
sed -i "s/IMAGE_VERSION/$IMAGE_VERSION/g" samconfig.toml
sed -i "s/CONTAINER_CPU/$CONTAINER_CPU/g" samconfig.toml
sed -i "s/CONTAINER_RAM/$CONTAINER_RAM/g" samconfig.toml


sam build
sam deploy -t ./template.yaml


echo '{"message" : "you did it, you really did it."}'
