version=0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "DEPLOYMENT_NAME"
s3_bucket = "DEPLOYMENT_NAME"
s3_prefix = "DEPLOYMENT_NAME/app"
region = "REGION"
confirm_changeset = CONFIRM_CHANGESET
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"APP_NAME\" ContainerImage=\"ECR_HOME/APP_NAME:IMAGE_VERSION\" ContainerCPU=\"CONTAINER_CPU\" ContainerRAM=\"CONTAINER_RAM\""

